version: '3.5'
services:
  mariadb:
    image: mariadb
    restart: always
    container_name: "mariadb"
    volumes:
      - "./db:/var/lib/mysql"
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=testDB3
      - MYSQL_USER=test3
      - MYSQL_PASSWORD=Password1!@
  web:
    build: .
    links:
      - mariadb
    container_name: Flyway-Service
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      - DB_PORT=3306
      - DB_NAME=testDB3
      - DB_HOST=mariadb
      - MYSQL_USER=test3
      - MYSQL_USER_PASSWORD=Password1!@
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - mariadb